# Generated by Django 4.2.17 on 2024-12-05 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ride',
            name='ride_ended',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
