# Generated by Django 4.1.4 on 2025-01-16 17:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dashboard', '0002_ride_ride_ended'),
    ]

    operations = [
        migrations.AddField(
            model_name='rfidcard',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rfid_cards', to=settings.AUTH_USER_MODEL),
        ),
    ]
