# Generated by Django 4.1.4 on 2025-01-16 17:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_rfidcard_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ride',
            name='card',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='dashboard.rfidcard'),
        ),
    ]
